# Copilot Setup Steps
# This file defines automated setup steps for GitHub Copilot coding agent
# to prepare the development environment

version: 1.0

setup:
  - name: Verify Node.js version
    description: Ensure Node.js 18 or higher is installed
    command: |
      node --version
    expected_output_contains: "v18"
    
  - name: Install dependencies
    description: Install npm dependencies (if any)
    command: |
      npm install
    working_directory: .
    
  - name: Verify Firebase CLI
    description: Check if Firebase CLI is available
    command: |
      npm list -g firebase-tools || npm install -g firebase-tools
    optional: true
    
  - name: Start local development server
    description: Start Python HTTP server for local testing
    command: |
      npm run serve-local &
    background: true
    optional: true
    
  - name: Verify Firebase configuration
    description: Check that Firebase config is present in index.html
    command: |
      grep -q "skatequest-666" index.html && echo "Firebase config found" || echo "Warning: Firebase config may be missing"
    
validation:
  - name: Check critical files exist
    description: Verify all critical files are present
    command: |
      test -f index.html && \
      test -f main.js && \
      test -f app.js && \
      test -f style.css && \
      test -f manifest.json && \
      test -f service-worker.js && \
      test -f firestore.rules && \
      test -f storage.rules && \
      echo "All critical files present"
      
  - name: Validate HTML structure
    description: Check that index.html is valid HTML5
    command: |
      if command -v html5validator &> /dev/null; then
        html5validator --root . --match index.html
      else
        echo "HTML validator not installed, skipping"
      fi
    optional: true
    
testing:
  - name: Run linter
    description: Lint JavaScript files
    command: |
      npx eslint app.js main.js || echo "Linting completed with warnings"
    optional: true
    
  - name: Check service worker syntax
    description: Verify service worker JavaScript is valid
    command: |
      node -c service-worker.js && echo "Service worker syntax valid"
    
  - name: Test local server access
    description: Verify local server responds (if running)
    command: |
      curl -s http://localhost:8000 > /dev/null && echo "Local server accessible" || echo "Local server not running"
    optional: true
    depends_on: "Start local development server"

cleanup:
  - name: Stop background processes
    description: Stop any background processes started during setup
    command: |
      pkill -f "python3 -m http.server" || true
    optional: true

notes:
  - This is a static site project with minimal build requirements
  - Firebase CLI is optional for development but required for rule deployment
  - Most testing is manual in the browser
  - No automated test suite is configured for this project
  - Use Chrome DevTools for debugging and PWA feature testing
