# Setup steps for GitHub Copilot coding agent
# This file helps the agent understand how to set up and work with this repository

name: SkateQuest App Setup

# Description of what this repository is
description: |
  SkateQuest is a static Progressive Web App (PWA) for skateboard spot discovery.
  No build process required - just serve the static files.

# Setup steps the agent should follow when working on this repo
steps:
  - name: Verify Node.js is available
    description: Check Node.js version for Firebase CLI and npm scripts
    run: node --version || echo "Node.js not found, but not required for static files"
    
  - name: Install dependencies (optional)
    description: Install dev dependencies if testing tools are needed
    run: |
      if [ -f "package.json" ]; then
        npm install --ignore-scripts || true
      fi
    
  - name: Start local development server
    description: Launch local server to test changes
    run: |
      # The preferred way to run the local server
      if command -v python3 &> /dev/null; then
        echo "Starting server with: python3 -m http.server 8000"
        echo "Access the app at http://localhost:8000"
      elif command -v python &> /dev/null; then
        echo "Starting server with: python -m http.server 8000"
        echo "Access the app at http://localhost:8000"
      else
        echo "Python not available. Install Python or use 'npm run serve-local'"
      fi
    manual: true
    
  - name: Verify Firebase configuration
    description: Ensure Firebase is properly configured in index.html
    run: |
      if grep -q "firebaseConfig" index.html; then
        echo "✓ Firebase configuration found in index.html"
      else
        echo "⚠ Firebase configuration missing from index.html"
      fi

# Key files to understand before making changes
key_files:
  - path: index.html
    description: Main entry point - Firebase SDK loaded via CDN
  - path: main.js
    description: Core app logic, challenge system, API helpers
  - path: app.js
    description: Extended user features and functionality
  - path: service-worker.js
    description: PWA service worker for offline caching
  - path: firestore.rules
    description: Firestore security rules
  - path: storage.rules
    description: Firebase Storage security rules
  - path: functions/index.js
    description: Firebase Cloud Functions for backend operations

# Technologies and tools
technologies:
  - name: HTML/CSS/JavaScript
    version: ES6+
    notes: Vanilla JavaScript, no framework or transpilation
  - name: Firebase
    version: SDK v9+ (via CDN)
    notes: Firestore, Storage, Auth, and Functions
  - name: Leaflet.js
    notes: Interactive mapping library
  - name: Python
    version: 3.x
    notes: Optional, for local development server

# Build and test commands (this is a static site)
build:
  command: echo "No build step required - static site"
  
test:
  command: npm test
  notes: No automated tests configured - manual browser testing required

# Linting
lint:
  command: npx eslint app.js main.js
  notes: Basic ESLint for JavaScript files

# Common workflows
workflows:
  - name: Local development
    steps:
      - Run local server with 'python3 -m http.server 8000' or 'npm run serve-local'
      - Open http://localhost:8000 in browser
      - Make changes to HTML/CSS/JS files
      - Refresh browser to see changes
      
  - name: Deploy Firebase rules
    steps:
      - Edit firestore.rules or storage.rules
      - Run './deploy.sh' or 'firebase deploy --only firestore:rules,storage:rules'
      - Verify in Firebase Console
      
  - name: Add a new feature
    steps:
      - Update HTML in index.html
      - Add JavaScript logic in main.js or app.js
      - Update styles in style.css
      - Test locally
      - If backend needed, add Cloud Function in functions/index.js

# Important patterns and conventions
patterns:
  - name: Firebase module access
    description: Use window.firebaseInstances to access Firebase modules
    example: |
      const { db, storage, doc, getDocs } = window.firebaseInstances;
    
  - name: Avoid bare imports
    description: Don't use ES6 imports for Firebase in browser code
    incorrect: import { getFirestore } from 'firebase/firestore'
    correct: const { db } = window.firebaseInstances;
    
  - name: Service worker cache updates
    description: Increment cache version when updating cached assets
    example: Change CACHE_NAME from 'skatequest-cache-v1' to 'skatequest-cache-v2'

# Security notes
security:
  - Firebase API keys in index.html are public and safe (protected by security rules)
  - Use GitHub Actions secrets for CI/CD tokens (FIREBASE_TOKEN)
  - All sensitive operations should be in Cloud Functions with auth checks
  - Never commit private credentials or tokens

# Documentation references
documentation:
  - START.md: Quick start guide
  - DEPLOY.md: Deployment instructions
  - AUTOMATION.md: Automation setup
  - PRODUCTION.md: Production environment
  - QUICK_REFERENCE.md: Common tasks reference
