mutation AddNewComment($authorId: UUID!, $observationId: UUID!, $text: String!) @auth(level: USER) {
  comment_insert(data: {authorId: $authorId, observationId: $observationId, text: $text, createdAt_expr: "request.time"})
}

query ListPublicObservations @auth(level: PUBLIC, insecureReason: "This query is safe to expose to the public") {
  observations(where: {isPublic: {eq: true}}) {
    id
    locationName
    observationDate
    observer {
      id
      username
    }
    celestialObject {
      id
      name
    }
  }
}

mutation UpdateUserBio($bio: String!) @auth(level: USER) {
  user_update(key: {id_expr: "auth.uid"}, data: {bio: $bio})
}

query GetMyWishlist @auth(level: USER) {
  wishlists(where: {userId_expr: "auth.uid"}) {
    celestialObject {
      id
      name
      type
      magnitude
    }
  }
}